### PR TITLE
refactor/pro-1160/remove-side-side-map

### PR DESCRIPTION
**Pull request by Janislav**
# Pull Request

Closes: PRO-1160

## Checklist

Please conduct a thorough self-review before opening the PR.

- [x] I am confident that the code works.
- [x] I have updated documentation where appropriate.

## Summary

*Please include a succinct description of the purpose and content of the PR. What problem does it solve, and how? Link issues, discussions, other PRs, and anything else that will help the reviewer.*

### CODE REVIEW

**Comment by Janislav** [comment]
@AlastairHolmes for now I kept the term `AssetsMap` because I actually think it's not the worst name. I changed the `Assets` enum to `Pairs`. Maybe because of that, the terminology `PoolPair` could make sense?

**Comment by AlastairHolmes** [comment]
Can we also rename: "to_sold_side" to "to_sold_pair"

**Comment by AlastairHolmes** [comment]
Also we should rename "enum Order" to "Side" in this PR too.

**Comment by AlastairHolmes** [comment]
> > @AlastairHolmes for now I kept the term `AssetsMap` because I actually think it's not the worst name. I changed the `Assets` enum to `Pairs`. Maybe because of that, the terminology `PoolPair` could make sense?
> 
> I like Pair/PoolPair, but wrt AssetsMap, I think its nice to keep consistently with the Map naming. So maybe (Pair, PairMap) / (Pairs, PairsMap) / (PoolPair, PoolPairMap) / (PoolPairs, PoolPairsMap)?

Lets stick with the Plural "Pairs"/"PoolPairs", as I want to use "PoolPair" for something else.

**Review by AlastairHolmes — APPROVED** [review]

**Pull request merged**
