### PR TITLE
chore(bouncer): Install fok sdk version

### PR DESCRIPTION
**Pull request by niklasnatter**
# Pull Request

Closes: PRO-xxx

## Checklist

Please conduct a thorough self-review before opening the PR.

- [ ] I am confident that the code works.
- [ ] I have updated documentation where appropriate.

## Summary

*Please include a succinct description of the purpose and content of the PR. What problem does it solve, and how? Link issues, discussions, other PRs, and anything else that will help the reviewer.*

#### Non-Breaking changes

If this PR includes non-breaking changes, select the `non-breaking` label. On merge, CI will automatically cherry-pick the commit to a PR against the release branch.

### CODE REVIEW

**Comment by albert-llimos** [comment]
@niklasnatter I assume this SDK doesn't include the Solana patches, right? If not, we'll need a version with FoK plus the Solana patches for the bouncer, as we plan to merge the Solana code as soon as we have a candidate for 1.5 release.

**Comment by niklasnatter** [comment]
> @niklasnatter I assume this SDK doesn't include the Solana patches, right? If not, we'll need a version with FoK plus the Solana patches for the bouncer, as we plan to merge the Solana code as soon as we have a candidate for 1.5 release.

No, not yet. I think it makes sense to merge the FoK branch in the SDK and update the Solana branch once we have a 1.5 candidate. Maybe we can even do it sooner to unblock you

**Comment by albert-llimos** [comment]
> > @niklasnatter I assume this SDK doesn't include the Solana patches, right? If not, we'll need a version with FoK plus the Solana patches for the bouncer, as we plan to merge the Solana code as soon as we have a candidate for 1.5 release.
> 
> No, not yet. I think it makes sense to merge the FoK branch in the SDK and update the Solana branch once we have a 1.5 candidate. Maybe we can even do it sooner to unblock you

Makes sense. Then I'll reach out when we are about to merge the Solana PR and we figure out the best solution.

**Comment by niklasnatter** [comment]
Replaced by https://github.com/chainflip-io/chainflip-backend/pull/5056

**Pull request closed without merging**
