### PR TITLE
fix: use blake account hasher.

### PR DESCRIPTION
**Pull request by dandanlen**
# Pull Request

Closes: PRO-1542

## Checklist

Please conduct a thorough self-review before opening the PR.

- [x] I am confident that the code works.
- [x] I have written sufficient tests.
- [x] I have written and tested required migrations.
- [x] I have updated documentation where appropriate.

## Summary

Use the blake2_128 hasher for affiliate accounts since they can be inserted by untrusted sources.

Doesn't need to be ported to the release branch.

### CODE REVIEW

**Review by dandanlen — COMMENTED** [review]
Now that i've opened the PR I'm not sure if it's worth merging - can probably be added to #5083...

**Review by kylezs — APPROVED** [review]
> Now that i've opened the PR I'm not sure if it's worth merging - can probably be added to https://github.com/chainflip-io/chainflip-backend/pull/5083...

Would say we can get it in and rebase - smaller PRs etc.

**Comment by Janislav** [comment]
As discussed, transferred the changes to my PR.

**Comment by dandanlen** [comment]
> > Now that i've opened the PR I'm not sure if it's worth merging - can probably be added to #5083...
> 
> Would say we can get it in and rebase - smaller PRs etc.

The will just disappear on the rebase. We'd just be adding another commit that will do nothing except add more work (merge conflicts, another migration...).

**Pull request closed without merging**
