### PR TITLE
[RC 1.6.4]

### PR DESCRIPTION
**Pull request by dandanlen**
Replaces #5243

### CODE REVIEW

**Comment by albert-llimos** [comment]
While my initial reaction was thinking that we should do this, I'm not so convinced anymore.
I think the reason Alastair implemented it with `all_same` is because the nonce mechanism is critical to the system and we really want to be totally sure that a nonce has changed before updating in the State Chain. Updating it with a wrong or old value would lead to an invalid transaction, which is extremely problematic in, for instance, a rotation transaction.
The downside of course is that one node could then keep reporting the wrong node and prevent the node from being updated. While I don't like this downside, when it comes to nonces I'd always prefer to be on the side of safety and compromise "liveliness" over signing invalid transactions.

**Comment by dandanlen** [comment]
@albert-llimos 

If we require unanimity then a single validator can prevent any nonce from being updated...

**Comment by albert-llimos** [comment]
> If we require unanimity then a single validator can prevent any nonce from being updated...

I acknowledged that in my comment. My point was that there was most certainly a reason why Alastair implement it that way (safety) and it's worth considering if there is some edge case that he considered in where we would want unanimity.
If we can't think of one or we just don't think we require more safety, then that's fine.

**Comment by dandanlen** [comment]
> > If we require unanimity then a single validator can prevent any nonce from being updated...
> 
> I acknowledged that in my comment. My point was that there was most certainly a reason why Alastair implement it that way (safety) and it's worth considering if there is some edge case that he thought about in which we would want unanimity. If we can't think of one or we just don't think we require more safety, then that's fine.

Maybe Alastair made a mistake? I don't think it adds more safety - it introduces a DoS vector.

I think the concern is that the validators might agree on some 'old' nonce, but requiring unanimity doesn't fix that: once we accept that a majority of validators might be wrong, we have to accept that they might all be wrong. I think the ultimate solution would be something like requiring them to witness (slot, nonce) and to require both a super-majority consensus on the nonce *and* that the consensus slot number increases.

**Comment by albert-llimos** [comment]
> I think the concern is that the validators might agree on some 'old' nonce, but requiring unanimity doesn't fix that: once we accept that a majority of validators might be wrong, we have to accept that they might all be wrong. I think the ultimate solution would be something like requiring them to witness (slot, nonce) and to require both a super-majority consensus on the nonce _and_ that the consensus slot number increases.
Makes sense. That was probably the concern, and I'd say it makes sense because in Solana it's not uncommon for nodes to fall behind, which is what your ultimate solution would address. But anyway yes, you're right, let's do this PR for now.

**Review by kylezs — APPROVED** [review]

**Pull request merged**
