### PR TITLE
fix: setup arb vault separately

### PR DESCRIPTION
**Pull request by kylezs**
Allows arb vault to be initialized later, as will be the case when we upgrade it.

Also fixes bug introduced here:
- #4764 the respective names weren't updated in the upgrade-test

### CODE REVIEW

**Review by albert-llimos — APPROVED** [review]
I just pushed a small refactor. LGTM!

**Comment by kylezs** [comment]
Just ensuring it works locally first.

**Comment by kylezs** [comment]
I'm going to wait for #4770 to be merged first. Then I'll squash the JS clean up changes made here and create a new PR

**Comment by kylezs** [comment]
Superseded by: https://github.com/chainflip-io/chainflip-backend/pull/4772
And #4770

**Pull request closed without merging**
