### PR TITLE
fix: continuous adapter

### PR DESCRIPTION
**Pull request by AlastairHolmes**
Basically, its an off by one error.

If the main stream misses the first block in an epoch, the continuous adapter would not fill the missed witness for that first block.

*Note if the engine was restarted it would fill in the gap.*

Looking at the code we were handling the last_processed_index and the start of the epoch in the same way, but the first is an index we don't want to process, but the second is an index we do want to process.

### CODE REVIEW

**Comment by msgmaxim** [comment]
Looks like something a unit test would have caught?

**Review by kylezs — APPROVED** [review]

**Comment by AlastairHolmes** [comment]
We're just waiting to do some extra testing before merging.

**Review by kylezs — APPROVED** [review]

**Comment by AlastairHolmes** [comment]
It's just a complex problem whose solution was rushed to meet a release deadline. It's bad code, so I think we'll rewrite it. https://linear.app/chainflip/issue/PRO-1280/re-write-continuous-adapter

**Comment by kylezs** [comment]
Tested manually to expedite release, will create a ticket to unit test.

**Pull request merged**
