### PR TITLE
Feat: Solana gas tweaks

### PR DESCRIPTION
**Pull request by albert-llimos**
# Pull Request

Closes: PRO-1501

## Checklist

Please conduct a thorough self-review before opening the PR.

- [x] I am confident that the code works.
- [ ] I have written sufficient tests.
- [ ] I have written and tested required migrations.
- [x] I have updated documentation where appropriate.

## Summary

- Set maximum CU per CCM transfer to 600k instead of 1.4M to avoid huge transactions which are less likely to be included by the leaders.
- Set a minimum of 1 priority fee (1 microlamport / CU), even if the median reported fee is zero. The cost of that priority fee will be negligible while it increases significantly the chances of being included.

### CODE REVIEW

**Comment by syan095** [comment]
Sorry for hijacking the PR. I've renamed `calculate_ccm_gas_limit` function so it's clearer that it's only used for CCM functions.

**Review by syan095 — APPROVED** [review]
LGMT!

**Comment by syan095** [comment]
1 question - we set the minimum "priority" fee to 1 - should we set this a bit higher?

**Comment by albert-llimos** [comment]
> 1 question - we set the minimum "priority" fee to 1 - should we set this a bit higher?

While setting it to one (microlamports/CU) looks and is very low, in normal conditions (not high congestion) of the network a priority fee of 1 should be enough. However, since we're really interested in inclusion and that amount is still very small it's reasonable to raise it to 10 for now. I'll do that.

**Pull request merged**
