### PR TITLE
Feat: add exclude fee quotes for Vault swaps

### PR DESCRIPTION
**Pull request by albert-llimos**
# Pull Request

Closes: PRO-1892

## Checklist

Please conduct a thorough self-review before opening the PR.

- [x] I am confident that the code works.
- [ ] I have written sufficient tests.
- [ ] I have written and tested required migrations.
- [ ] I have updated documentation where appropriate.

## Summary

Implemented on top of the ccm gas improvement since it's adding a new parameter to the already changed functions. No need to to the same versioning update in a separate PR.

### CODE REVIEW

**Review by dandanlen — COMMENTED** [review]
Approach LGTM but I'd like to take a closer look at the runtime api changes - looks like a breaking change in the runtime api. If/How we need to deal with this depends on how it compares to the current release version. 

@albert-llimos if it's ok i'll take a look later and will update the PR directly.

**Comment by albert-llimos** [comment]
> Approach LGTM but I'd like to take a closer look at the runtime api changes - looks like a breaking change in the runtime api. If/How we need to deal with this depends on how it compares to the current release version.
> 
> @albert-llimos if it's ok i'll take a look later and will update the PR directly.

Notice that the change adding `exclude_fees` is on the funcitons that the PR underneath has also added `ccm_data`. If you have reviewed this I'd suggest merging it to the main PR and then review those api changes all together. Are you ok with that @dandanlen ?

**Comment by dandanlen** [comment]
Let me make some small changes first.

**Comment by dandanlen** [comment]
@albert-llimos all done ☝️ 

Feel free to merge unless you have any objections to the changes. 

- I felt including the broker fee in the enum was not necessary since it's implicit in the amount: if amount is greater than zero that means you want to include it. 
- Using a btreeSet is helpful since it already deduplicates the values. 
- Using an option in the runtime api doesn't add anything (in contrast with the json api where using an Option<> makes the field optional, SCALE encoding still requires a `None`)
- Factored out the !exluded checks into a closure `included`

**Comment by albert-llimos** [comment]
LGTM, thanks!

**Pull request merged**
