### PR TITLE
Chore: rename cf_asset_balances to cf_asset_free_balances

### PR DESCRIPTION
**Pull request by marcellorigotti**
# Pull Request

Closes: PRO-xxx

## Checklist

Please conduct a thorough self-review before opening the PR.

- [x] I am confident that the code works.
- [x] I have updated documentation where appropriate.

## Summary

Renamed custom rpc method to better reflect the actual behaviour, while keeping the old one for backwards compatibility as alias.

#### Non-Breaking changes

### CODE REVIEW

**Review by AlastairHolmes — COMMENTED** [review]
Looks good, butcan you do the same for the LP-APIs: asset_balances rpc too.

**Comment by marcellorigotti** [comment]
Update lp-api as well!

**Review by AlastairHolmes — APPROVED** [review]

**Comment by dandanlen** [comment]
How about cf_free_balances instead? The 'asset' in the middle is a little redundant, no?

**Comment by AlastairHolmes** [comment]
I think we should also change all the internal asset_balance functions to match the new naming.

**Comment by marcellorigotti** [comment]
Updated variable and functions to match free_balances

**Review by AlastairHolmes — APPROVED** [review]

**Pull request merged**
