### PR TITLE
feat: Punish nodes that do not witness in time

### PR DESCRIPTION
**Pull request by syan095**
# Pull Request

Closes: PRO-1004

## Checklist

Please conduct a thorough self-review before opening the PR.

- [x] I am confident that the code works.
- [x] I have updated documentation where appropriate.

## Summary

When witnessed calls are dispatched, a deadline is set for remaining authorities to witness. 
Once the deadline is up, any nodes that failed to witness the all are reported to be punished

### CODE REVIEW

**Comment by kylezs** [comment]
assigned myself as reviewer just to check there's no impact to how the CFE is witnessing

**Review by dandanlen — APPROVED** [review]
Good work @syan095 

I made some changes to the implementation to avoid re-reading storage and building the vote count lookup for every loop iteration. 

If you're happy with this, please merge.

**Comment by dandanlen** [comment]
Btw. we will have to remember to set a penalty for this when we actually roll it out.

**Comment by kylezs** [comment]
Looks like nothing touching CFE side 👍

**Comment by kylezs** [comment]
> Btw. we will have to remember to set a penalty for this when we actually roll it out.

Does this mean we won't see any penalties on localnet and the like?

**Pull request merged**
